version: '2.27'

services:
  web:
    build:
      context: ./web
    container_name: web_service
    ports:
      - "5000:5000"
    environment:
      - HOST=0.0.0.0
      - PORT=5000
    networks:
      - webnet

  load_balancer:
    build:
      context: ./load_balancer
    container_name: load_balancer
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - webnet

networks:
  webnet:
